### ISSUE TITLE
"empty" IP (V3.2019.02.1055) - not working

### ISSUE THREAD

**Issue by ShaiMagal** [mitchellkrogza/apache-ultimate-bad-bot-blocker#115]
After last update (V3.2019.02.1055) it is not working because line:
# START WP THEME DETECTORS ### DO NOT EDIT THIS LINE AT ALL ###
	Require not ip 
	Require not ip 104.197.51.76
(not IP is provided on first line after comment)

**Comment by mitchellkrogza** [comment]
Thanks for reporting will be addressed within the hour. Apologies

**Comment by mitchellkrogza** [comment]
@ShaiMagal fixed in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/f89b504e9d0a58223d47142c9dd28a5b8c1c09b6 thanks again for reporting. The Build Process revealed a serious bug which has now also been addressed and fixed to force any builds in future to fail as a result from such a bug. Sincere apologies for any interruptions.
