### ISSUE TITLE
What is good, what is not?

### ISSUE THREAD

**Issue by DarkZeroCD** [mitchellkrogza/apache-ultimate-bad-bot-blocker#15]
I share a few days of my logs
I would like to know what is good or not, according to you.
Pingdom for example?

> 6481 Mozilla/5.0
> 557 Apache/2.4.10
> 62 Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)
> 55 Mozilla/4.0
> 46 
> 19 msnbot-media/1.1
> 12 rogerbot/1.0
> 10 Camo
> 5 Twitterbot/1.0
> 5 Opera/9.80
> 3 Safari/12602.1.50.0.10
> 2 python-requests/2.2.1
> 2 Jersey/2.25
> 2 git/2.1.4
> 1 Java/1.8.0_121

> 7552 Mozilla/5.0
> 783 Apache/2.4.10
> 168 
> 91 Mozilla/4.0
> 58 Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)
> 19 msnbot-media/1.1
> 12 rogerbot/1.0
> 10 -
> 8 yacybot
> 6 Camo
> 5 Twitterbot/1.0
> 3 Safari/12603.1.30.0.34
> 2 python-requests/2.2.1
> 1 Java/1.8.0_121

> 7494 Mozilla/5.0
> 719 Apache/2.4.10
> 130 
> 62 Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)
> 57 Mozilla/4.0
> 12 yacybot
> 12 rogerbot/1.0
> 12 msnbot-media/1.1
> 12 Camo
> 8 Opera/9.80
> 8 Mozilla
> 7 Sogou
> 6 -
> 5 Twitterbot/1.0
> 5 MobileSafari/602.1
> 4 Wget(linux)
> 3 Safari/12603.1.30.0.34
> 2 Safari/12603.2.1
> 2 python-requests/2.2.1
> 1 Java/1.8.0_121
> 1 Go-http-client/1.1

> 19356 Mozilla/5.0
> 907 Apache/2.4.10
> 66 
> 64 Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)
> 55 Mozilla/4.0
> 22 msnbot-media/1.1
> 14 yacybot
> 12 rogerbot/1.0
> 6 Twitterbot/1.0
> 4 Camo
> 3 Safari/12602.4.8
> 2 WinHTTP
> 2 python-requests/2.2.1
> 1 Scanbot
> 1 Python-urllib/3.4
> 1 Java/1.8.0_121

> 6914 Mozilla/5.0
> 1023 Apache/2.4.10
> 824 
> 64 Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)
> 61 Mozilla/4.0
> 12 rogerbot/1.0
> 11 Opera/9.80
> 10 yacybot
> 9 -
> 8 msnbot-media/1.1
> 6 Camo
> 4 Safari/12603.1.30.0.34
> 4 Feedly/1.0
> 2 python-requests/2.2.1
> 1 Opera/7.11
> 1 Java/1.8.0_121

**Comment by mitchellkrogza** [comment]
I will dig deeper into
```
Camo
yacybot
```

Pingdom.com though is perfectly fine and safe, their network tools are very useful for diagnosing server faults. If you don't want them to access your servers wait for some changes later this week which will allow you to have your own custom blacklist of user-agents as I have done in the https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker

```
rogerbot
scanbot
```

are already blocked

and

`Mozilla/5.0` is valid user agent string even still used in the latest version of Firefox 51.0

A lot of bad bots fake their user agent string to `Mozilla/5.0` because they know people cannot block that. If you have any particular aggressive bot continuing to hammer your site you will need to look at blocking them IP rather.

Again there will be changes to this repo later this week allowing you to also build your own custom blacklist of IP addresses and ranges that won;t get overwritten with my latest updates.

**Comment by mitchellkrogza** [comment]
Camo for now seems ok - https://github.com/atmos/camo

Some people seem to be complaining about Yacybot - their site says they respect robots.txt
http://yacy.net/bot.html

Wait for changes later this week which will allow you choose if you want to block those or not using your own custom lists.

**Comment by DarkZeroCD** [comment]
Thanks a lot for all these informations!
Camo is good, it's me who is set up.

I do not want to have any analysis tools on my site, even if they are trusted bots like Google or Pingdom.
I will wait for your next upgrades that I look forward to! :)

**Comment by mitchellkrogza** [comment]
No problem big update coming tomorrow morning. This will allow a lot more
custom control for users.

**Comment by mitchellkrogza** [comment]
@DarkZeroCD New Custom Include Files Introduced today in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/releases/tag/2017-04-19.Build-173 PLEASE READ UPDATED INSTRUCTIONS !!!!
