### ISSUE TITLE
Need Spam Whitelist

### ISSUE THREAD

**Issue by MediaSnog** [mitchellkrogza/apache-ultimate-bad-bot-blocker#21]
There is a need for a spam whitelist file due to checking individual words in the globalblacklist.conf file.

A url with a page that legitimately includes a word in the list gets a 403 error. Even if that site is listed in the domain whitelist.

Example:
http://adomain.com/threads/utahs-war-on-smut-and-the-lesbian-mormon-pornographer.10990/

Or, move the spam words to a separate conf file so it can be optionally included.

**Comment by mitchellkrogza** [comment]
Thanks for the alert. I am indeed moving the spam words to become an
include file that can be customized and also introducing another include to
move the blacklist ip’s to an include file so people can customize that as
they like.

Those changes coming in this week, I delayed them due to Easter and people
being away from their servers.

Happy Easter


From: MediaSnog <notifications@github.com> <notifications@github.com>
Reply: mitchellkrogza/apache-ultimate-bad-bot-blocker
<reply@reply.github.com>
<reply@reply.github.com>
Date: 16 April 2017 at 3:43:14 PM
To: mitchellkrogza/apache-ultimate-bad-bot-blocker
<apache-ultimate-bad-bot-blocker@noreply.github.com>
<apache-ultimate-bad-bot-blocker@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  [mitchellkrogza/apache-ultimate-bad-bot-blocker] Need Spam
Whitelist (#21)

There is a need for a spam whitelist file due to checking individual words
in the globalblacklist.conf file.

A url with a page that legitimately includes a word in the list gets a 403
error. Even if that site is listed in the domain whitelist.

Example:
http://adomain.com/threads/utahs-war-on-smut-and-the-lesbian-mormon-pornographer.10990/

Or, move the spam words to a separate conf file so it can be optionally
included.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/issues/21>,
or mute the thread

**Comment by mitchellkrogza** [comment]
@MediaSnog  please make sure you are subscribe to the repo notifications so when I push out the changes this week you will be notified. It's important once I do the update to get the new include files onto your server otherwise the update script or an apache reload will fail without the presence of the new include files.

**Comment by mitchellkrogza** [comment]
@MediaSnog Introduced today in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/releases/tag/2017-04-19.Build-173 PLEASE READ UPDATED INSTRUCTIONS !!!!
