### ISSUE TITLE
User-Agents Whitelist

### ISSUE THREAD

**Issue by eenov** [mitchellkrogza/apache-ultimate-bad-bot-blocker#34]
Hi there !

First thanks for your work ! It saves me from some bad bots on some old sites !

I'd like to suggest an improvement, i have a use case in which i'd like to whitelist an user agent (Indy Library, already blacklisted in the globalblacklist.conf). This user agent is used in a scheduled task launch ed by a windows server via a custom software linked to Sage.

Is it possible to add an include file "whitelist-user-agents.conf" at the beginning of the file and an order directive like : 

Order Allow, Deny
Allow from env=good_bot 
Deny from env=bad_bot 

Actually, there is only Deny from env=bad_bot. 

PS : Maybe it can be applied to bad-referrer too ?

Regards,

Julien Faure EENOV

**Comment by mitchellkrogza** [comment]
Thanks @eenov I am indeed busy revising the ordering of whitelisting vs blacklisting in the script to get ordering correct so that even if something is blacklisted the whitelist you add will over-ride it. Just busy moving all the generator scripts into the repo first so that Travis does all generating of the lists itself including testing them before pushing out a release. That scripting should be in place tomorrow then I will sort out this current issue. Thanks for your support and for notifying me about this, already in the pipeline 👍

**Comment by eenov** [comment]
Thank you for your quick reply ! 

I just comment out the line for the current user agent for now, and it works flawlessly.

**Comment by mitchellkrogza** [comment]
@eenov To avoid any breaking changes by introducing a new required include file like whitelist-user-agents.conf why not user the blacklist-user-agents.conf and do any whitelisting there. It should over-ride anything above it that's already blacklisted (not tested) but worth a try. I'll test tomorrow.

So in your blacklist-user-agents.conf try this

```
BrowserMatchNoCase "^(.*?)(\bIndy\ Library\b)(.*)$" good_bot
```

Let me know. Also please note all the recent updates. Existing version you are using is now in a folder called Apache_2.2 and old version in root conf.d folder is going to be deprecated soon.

**Comment by eenov** [comment]
Thanks ! I'll update the app next week and try that. The "order=Allow,Deny" you put in main should do the trick. I'll post the results here.

**Comment by mitchellkrogza** [comment]
Cool let me know. Also note some of the include files have been updated to
reflect the new regex formatting and also the blacklist-user-agents include
file has some commenting  regarding both whitelisting and blacklisting.
Keep me updated.
