### ISSUE TITLE
Relative paths for includes?

### ISSUE THREAD

**Issue by GutHib** [mitchellkrogza/apache-ultimate-bad-bot-blocker#59]
Hi,

Just installed the bad bot blocker - everything looks good so far, thanks for the hard work!

I have a question, though: Since different setups/control panels (also the popular ones) may use different directory structures, would it be possible to set up the includes in globalblacklist.conf as relative paths instead of absolute ones? That way, everyone would have a chance to use the automatic updates without the hard-wired paths breaking functionality.

Also, to update those whitelists, is there any chance to grab the domains from one of the files already present on the system (vhosts or whatever else)? I was somehow hoping for a setup that would have any new domain additions covered by default.

Thanks!

**Comment by mitchellkrogza** [comment]
Hi @GutHib my sincere apologies for not replying, Firstly compliments of the season to you and wish you all the best for 2018.

My 2017 did not end of well with me being ill for several weeks and I fell seriously behind with things hence my reply only now.

I hope the blocker is still working well for you, updates and improvments have resumed for 2018 and I certainly will test using relative paths instead of hard wired. Have you tested yourself by manually modifying globalblacklist.conf with relative paths to see that it works? If so please post your examples here as it will save me time.

**Comment by GutHib** [comment]
Thanks for the update, and a healthy 2018 to you!

@globalblacklist.conf: I'm afraid I haven't tried - I simply set up everything with my own absolute paths for now.

**Comment by mitchellkrogza** [comment]
Mind sharing your path structures you use so I can test?

**Comment by mitchellkrogza** [comment]
@GutHib any feedback on this? our new paths might resolve this. Latest updates have new paths. Let me know.

**Comment by GutHib** [comment]
First of all, sorry for the late reply. The new paths work great (some adjustment left to do on my end, but the important thing is I can work with the original files and therefore use automatic updates).

Well, at least in theory. I've discovered today that, with my nginx+apache setup, I need to use the nginx blocker instead. :) I'll continue with my feedback over there...

**Comment by mitchellkrogza** [comment]
Perfect, closing this.
